### PR TITLE
feat(lambda): alarming and dashboard support for success percentage

### PR DESCRIPTION
**Pull request by zorbasd**
- Add lambda success percentage metric.
- Add lambda success percentage alarm.
- Add lambda success percentage dashboard widget.

Fixes #

---

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_

### CODE REVIEW

**Review by echeung-amzn — CHANGES_REQUESTED** [review]
LGTM, but can you also mention this in the features table in `README.md`?

**Comment by voho** [comment]
Thanks for the contribution! How does the lambda monitoring section look like after the change? Do you have any screenshot? If we are modifying the defaults, we should be super careful not to break the layout for the existing users.

**Comment by niebloomj** [comment]
Would love to see some screenshots here

**Comment by echeung-amzn** [comment]
Closing abandoned PR.

**Pull request closed without merging**
